name: browserstack workflow

on:
  workflow_call:
    secrets:
      BROWSERSTACK_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Request if Browserstack has available spots
        run: | 
          while true; do
            response=$(curl -u ${{ secrets.BROWSERSTACK_KEY }} https://api.browserstack.com/automate/plan.json)
            echo "RESPONSE=$response" >> $GITHUB_OUTPUT
            if [[ $response | jq '.parallel_sessions_running < .parallel_sessions_max_allowed' ]]; then
              break
            fi
            sleep 10
          done
        id: availability-request

      # - name: Parse availability from Browserstack
      #   run: |
      #     parallel_sessions_running=$(echo '${{ steps.availability-request.outputs.RESPONSE }}' | jq -r '.parallel_sessions_running')
      #     parallel_sessions_max_allowed=$(echo '${{ steps.availability-request.outputs.RESPONSE }}' | jq -r '.parallel_sessions_max_allowed')
      #     echo "SESSIONS_RUNNING=$parallel_sessions_running" >> $GITHUB_OUTPUT
      #     echo "MAX_ALLOWED_SESSIONS=$parallel_sessions_max_allowed" >> $GITHUB_OUTPUT
      #   id: parse-availability-response
      #   continue-on-error: true
      # - name: Use params in next step
      #   run: |
      #     echo "Parallel running: ${{ steps.parse-availability-response.outputs.SESSIONS_RUNNING}}"
      #     echo "Max Parallel: ${{ steps.parse-availability-response.outputs.MAX_ALLOWED_SESSIONS}}"