name: iterate artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Create text files
      run: |
        echo "Hello, world!" > file1.txt
        echo "Goodbye, world!" > file2.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: ./*.txt

    - name: Iterate over artifacts
      run: |
        for artifact in ${{ steps.list-urls.outputs.artifacts }}; do
          echo "Artifact URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/raw/${{ github.ref }}/${artifact}"
        done
